wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.3
background_noise_level_indist:
  desc: null
  value: 0
background_noise_level_outdist:
  desc: null
  value: 100
bs:
  desc: null
  value: 64
color_theme_indist:
  desc: null
  value: 2
color_theme_outdist:
  desc: null
  value: 0
color_theme_road_indist:
  desc: null
  value: 0
color_theme_road_outdist:
  desc: null
  value: 3
