wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.3
method:
  desc: null
  value: grid
metric:
  desc: null
  value:
    goal: maximize
    name: score_outdist
name:
  desc: null
  value: domain randomization 0
parameters:
  desc: null
  value:
    background_noise_level_indist:
      values:
      - 0
    background_noise_level_outdist:
      values:
      - 100
    bs:
      value: 64
    color_theme_indist:
      values:
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    color_theme_outdist:
      values:
      - 0
      - 1
    color_theme_road_indist:
      values:
      - 0
      - 1
      - 4
      - 5
      - 6
      - 7
    color_theme_road_outdist:
      values:
      - 2
      - 3
